#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="memoriafamiliar")]
	public partial class JuizoFinalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertJuizofinal_cliente_falecido(Juizofinal_cliente_falecido instance);
    partial void UpdateJuizofinal_cliente_falecido(Juizofinal_cliente_falecido instance);
    partial void DeleteJuizofinal_cliente_falecido(Juizofinal_cliente_falecido instance);
    partial void InsertJuizofinal_dados_pagseguro(Juizofinal_dados_pagseguro instance);
    partial void UpdateJuizofinal_dados_pagseguro(Juizofinal_dados_pagseguro instance);
    partial void DeleteJuizofinal_dados_pagseguro(Juizofinal_dados_pagseguro instance);
    partial void InsertJuizofinal_falecido(Juizofinal_falecido instance);
    partial void UpdateJuizofinal_falecido(Juizofinal_falecido instance);
    partial void DeleteJuizofinal_falecido(Juizofinal_falecido instance);
    partial void InsertJuizofinal_cliente(Juizofinal_cliente instance);
    partial void UpdateJuizofinal_cliente(Juizofinal_cliente instance);
    partial void DeleteJuizofinal_cliente(Juizofinal_cliente instance);
    partial void InsertJuizofinal_jazigo(Juizofinal_jazigo instance);
    partial void UpdateJuizofinal_jazigo(Juizofinal_jazigo instance);
    partial void DeleteJuizofinal_jazigo(Juizofinal_jazigo instance);
    #endregion
		
		public JuizoFinalDataContext() : 
				base(global::DAO.Properties.Settings.Default.memoriafamiliarConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JuizoFinalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JuizoFinalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JuizoFinalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JuizoFinalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Juizofinal_cliente_falecido> Juizofinal_cliente_falecidos
		{
			get
			{
				return this.GetTable<Juizofinal_cliente_falecido>();
			}
		}
		
		public System.Data.Linq.Table<Juizofinal_dados_pagseguro> Juizofinal_dados_pagseguros
		{
			get
			{
				return this.GetTable<Juizofinal_dados_pagseguro>();
			}
		}
		
		public System.Data.Linq.Table<Juizofinal_falecido> Juizofinal_falecidos
		{
			get
			{
				return this.GetTable<Juizofinal_falecido>();
			}
		}
		
		public System.Data.Linq.Table<Juizofinal_nivel_parentesco> Juizofinal_nivel_parentescos
		{
			get
			{
				return this.GetTable<Juizofinal_nivel_parentesco>();
			}
		}
		
		public System.Data.Linq.Table<Juizofinal_nivel_corporacao> Juizofinal_nivel_corporacaos
		{
			get
			{
				return this.GetTable<Juizofinal_nivel_corporacao>();
			}
		}
		
		public System.Data.Linq.Table<Juizofinal_cliente> Juizofinal_clientes
		{
			get
			{
				return this.GetTable<Juizofinal_cliente>();
			}
		}
		
		public System.Data.Linq.Table<Juizofinal_jazigo> Juizofinal_jazigos
		{
			get
			{
				return this.GetTable<Juizofinal_jazigo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Juizofinal_cliente_falecido")]
	public partial class Juizofinal_cliente_falecido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_cliente;
		
		private int _ID_falecido;
		
		private bool _Ativo;
		
		private System.DateTime _DT_Inclusao;
		
		private System.Nullable<System.DateTime> _DT_Alteracao;
		
		private System.Nullable<System.DateTime> _DT_Exclusao;
		
		private EntityRef<Juizofinal_falecido> _Juizofinal_falecido;
		
		private EntityRef<Juizofinal_cliente> _Juizofinal_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_clienteChanging(int value);
    partial void OnID_clienteChanged();
    partial void OnID_falecidoChanging(int value);
    partial void OnID_falecidoChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    partial void OnDT_InclusaoChanging(System.DateTime value);
    partial void OnDT_InclusaoChanged();
    partial void OnDT_AlteracaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_AlteracaoChanged();
    partial void OnDT_ExclusaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_ExclusaoChanged();
    #endregion
		
		public Juizofinal_cliente_falecido()
		{
			this._Juizofinal_falecido = default(EntityRef<Juizofinal_falecido>);
			this._Juizofinal_cliente = default(EntityRef<Juizofinal_cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_cliente
		{
			get
			{
				return this._ID_cliente;
			}
			set
			{
				if ((this._ID_cliente != value))
				{
					if (this._Juizofinal_cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_clienteChanging(value);
					this.SendPropertyChanging();
					this._ID_cliente = value;
					this.SendPropertyChanged("ID_cliente");
					this.OnID_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_falecido", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_falecido
		{
			get
			{
				return this._ID_falecido;
			}
			set
			{
				if ((this._ID_falecido != value))
				{
					if (this._Juizofinal_falecido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_falecidoChanging(value);
					this.SendPropertyChanging();
					this._ID_falecido = value;
					this.SendPropertyChanged("ID_falecido");
					this.OnID_falecidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Inclusao", DbType="DateTime NOT NULL")]
		public System.DateTime DT_Inclusao
		{
			get
			{
				return this._DT_Inclusao;
			}
			set
			{
				if ((this._DT_Inclusao != value))
				{
					this.OnDT_InclusaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Inclusao = value;
					this.SendPropertyChanged("DT_Inclusao");
					this.OnDT_InclusaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Alteracao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Alteracao
		{
			get
			{
				return this._DT_Alteracao;
			}
			set
			{
				if ((this._DT_Alteracao != value))
				{
					this.OnDT_AlteracaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Alteracao = value;
					this.SendPropertyChanged("DT_Alteracao");
					this.OnDT_AlteracaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Exclusao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Exclusao
		{
			get
			{
				return this._DT_Exclusao;
			}
			set
			{
				if ((this._DT_Exclusao != value))
				{
					this.OnDT_ExclusaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Exclusao = value;
					this.SendPropertyChanged("DT_Exclusao");
					this.OnDT_ExclusaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Juizofinal_falecido_Juizofinal_cliente_falecido", Storage="_Juizofinal_falecido", ThisKey="ID_falecido", OtherKey="ID_falecido", IsForeignKey=true)]
		public Juizofinal_falecido Juizofinal_falecido
		{
			get
			{
				return this._Juizofinal_falecido.Entity;
			}
			set
			{
				Juizofinal_falecido previousValue = this._Juizofinal_falecido.Entity;
				if (((previousValue != value) 
							|| (this._Juizofinal_falecido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Juizofinal_falecido.Entity = null;
						previousValue.Juizofinal_cliente_falecidos.Remove(this);
					}
					this._Juizofinal_falecido.Entity = value;
					if ((value != null))
					{
						value.Juizofinal_cliente_falecidos.Add(this);
						this._ID_falecido = value.ID_falecido;
					}
					else
					{
						this._ID_falecido = default(int);
					}
					this.SendPropertyChanged("Juizofinal_falecido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Juizofinal_cliente_Juizofinal_cliente_falecido", Storage="_Juizofinal_cliente", ThisKey="ID_cliente", OtherKey="ID_cliente", IsForeignKey=true)]
		public Juizofinal_cliente Juizofinal_cliente
		{
			get
			{
				return this._Juizofinal_cliente.Entity;
			}
			set
			{
				Juizofinal_cliente previousValue = this._Juizofinal_cliente.Entity;
				if (((previousValue != value) 
							|| (this._Juizofinal_cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Juizofinal_cliente.Entity = null;
						previousValue.Juizofinal_cliente_falecidos.Remove(this);
					}
					this._Juizofinal_cliente.Entity = value;
					if ((value != null))
					{
						value.Juizofinal_cliente_falecidos.Add(this);
						this._ID_cliente = value.ID_cliente;
					}
					else
					{
						this._ID_cliente = default(int);
					}
					this.SendPropertyChanged("Juizofinal_cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Juizofinal_dados_pagseguro")]
	public partial class Juizofinal_dados_pagseguro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cod_transacao;
		
		private int _ID_Usuario;
		
		private string _codigo_carrinho;
		
		private string _codigo_pagto_transacao;
		
		private System.DateTime _Data_Insercao;
		
		private System.Nullable<System.DateTime> _Data_Alteracao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCod_transacaoChanging(int value);
    partial void OnCod_transacaoChanged();
    partial void OnID_UsuarioChanging(int value);
    partial void OnID_UsuarioChanged();
    partial void Oncodigo_carrinhoChanging(string value);
    partial void Oncodigo_carrinhoChanged();
    partial void Oncodigo_pagto_transacaoChanging(string value);
    partial void Oncodigo_pagto_transacaoChanged();
    partial void OnData_InsercaoChanging(System.DateTime value);
    partial void OnData_InsercaoChanged();
    partial void OnData_AlteracaoChanging(System.Nullable<System.DateTime> value);
    partial void OnData_AlteracaoChanged();
    #endregion
		
		public Juizofinal_dados_pagseguro()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cod_transacao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cod_transacao
		{
			get
			{
				return this._Cod_transacao;
			}
			set
			{
				if ((this._Cod_transacao != value))
				{
					this.OnCod_transacaoChanging(value);
					this.SendPropertyChanging();
					this._Cod_transacao = value;
					this.SendPropertyChanged("Cod_transacao");
					this.OnCod_transacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Usuario", DbType="Int NOT NULL")]
		public int ID_Usuario
		{
			get
			{
				return this._ID_Usuario;
			}
			set
			{
				if ((this._ID_Usuario != value))
				{
					this.OnID_UsuarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Usuario = value;
					this.SendPropertyChanged("ID_Usuario");
					this.OnID_UsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_carrinho", DbType="VarChar(100)")]
		public string codigo_carrinho
		{
			get
			{
				return this._codigo_carrinho;
			}
			set
			{
				if ((this._codigo_carrinho != value))
				{
					this.Oncodigo_carrinhoChanging(value);
					this.SendPropertyChanging();
					this._codigo_carrinho = value;
					this.SendPropertyChanged("codigo_carrinho");
					this.Oncodigo_carrinhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo_pagto_transacao", DbType="VarChar(100)")]
		public string codigo_pagto_transacao
		{
			get
			{
				return this._codigo_pagto_transacao;
			}
			set
			{
				if ((this._codigo_pagto_transacao != value))
				{
					this.Oncodigo_pagto_transacaoChanging(value);
					this.SendPropertyChanging();
					this._codigo_pagto_transacao = value;
					this.SendPropertyChanged("codigo_pagto_transacao");
					this.Oncodigo_pagto_transacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Insercao", DbType="DateTime NOT NULL")]
		public System.DateTime Data_Insercao
		{
			get
			{
				return this._Data_Insercao;
			}
			set
			{
				if ((this._Data_Insercao != value))
				{
					this.OnData_InsercaoChanging(value);
					this.SendPropertyChanging();
					this._Data_Insercao = value;
					this.SendPropertyChanged("Data_Insercao");
					this.OnData_InsercaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_Alteracao", DbType="DateTime")]
		public System.Nullable<System.DateTime> Data_Alteracao
		{
			get
			{
				return this._Data_Alteracao;
			}
			set
			{
				if ((this._Data_Alteracao != value))
				{
					this.OnData_AlteracaoChanging(value);
					this.SendPropertyChanging();
					this._Data_Alteracao = value;
					this.SendPropertyChanged("Data_Alteracao");
					this.OnData_AlteracaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Juizofinal_falecido")]
	public partial class Juizofinal_falecido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_falecido;
		
		private System.Nullable<int> _ID_falecido_Pai;
		
		private string _Nome_falecido;
		
		private System.Nullable<System.DateTime> _data_nasceimento;
		
		private System.Nullable<System.DateTime> _data_morte;
		
		private string _epitafio;
		
		private bool _Ativo;
		
		private System.DateTime _DT_Inclusao;
		
		private System.Nullable<System.DateTime> _DT_Alteracao;
		
		private System.Nullable<System.DateTime> _DT_Exclusao;
		
		private string _Nome_falecido_busca;
		
		private string _Nome_mae;
		
		private string _Nome_pai;
		
		private string _cidade_nascimento;
		
		private string _cidade_morte;
		
		private string _causa_morte;
		
		private string _foto_1;
		
		private string _foto_2;
		
		private string _foto_3;
		
		private System.Nullable<int> _estrelas_brancas;
		
		private System.Nullable<int> _estrelas_azuis;
		
		private System.Nullable<int> _estrelas_vermelhas;
		
		private System.Nullable<int> _vela;
		
		private string _profissao;
		
		private EntitySet<Juizofinal_cliente_falecido> _Juizofinal_cliente_falecidos;
		
		private EntitySet<Juizofinal_falecido> _Juizofinal_falecidos;
		
		private EntityRef<Juizofinal_falecido> _Juizofinal_falecido1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_falecidoChanging(int value);
    partial void OnID_falecidoChanged();
    partial void OnID_falecido_PaiChanging(System.Nullable<int> value);
    partial void OnID_falecido_PaiChanged();
    partial void OnNome_falecidoChanging(string value);
    partial void OnNome_falecidoChanged();
    partial void Ondata_nasceimentoChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_nasceimentoChanged();
    partial void Ondata_morteChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_morteChanged();
    partial void OnepitafioChanging(string value);
    partial void OnepitafioChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    partial void OnDT_InclusaoChanging(System.DateTime value);
    partial void OnDT_InclusaoChanged();
    partial void OnDT_AlteracaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_AlteracaoChanged();
    partial void OnDT_ExclusaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_ExclusaoChanged();
    partial void OnNome_falecido_buscaChanging(string value);
    partial void OnNome_falecido_buscaChanged();
    partial void OnNome_maeChanging(string value);
    partial void OnNome_maeChanged();
    partial void OnNome_paiChanging(string value);
    partial void OnNome_paiChanged();
    partial void Oncidade_nascimentoChanging(string value);
    partial void Oncidade_nascimentoChanged();
    partial void Oncidade_morteChanging(string value);
    partial void Oncidade_morteChanged();
    partial void Oncausa_morteChanging(string value);
    partial void Oncausa_morteChanged();
    partial void Onfoto_1Changing(string value);
    partial void Onfoto_1Changed();
    partial void Onfoto_2Changing(string value);
    partial void Onfoto_2Changed();
    partial void Onfoto_3Changing(string value);
    partial void Onfoto_3Changed();
    partial void Onestrelas_brancasChanging(System.Nullable<int> value);
    partial void Onestrelas_brancasChanged();
    partial void Onestrelas_azuisChanging(System.Nullable<int> value);
    partial void Onestrelas_azuisChanged();
    partial void Onestrelas_vermelhasChanging(System.Nullable<int> value);
    partial void Onestrelas_vermelhasChanged();
    partial void OnvelaChanging(System.Nullable<int> value);
    partial void OnvelaChanged();
    partial void OnprofissaoChanging(string value);
    partial void OnprofissaoChanged();
    #endregion
		
		public Juizofinal_falecido()
		{
			this._Juizofinal_cliente_falecidos = new EntitySet<Juizofinal_cliente_falecido>(new Action<Juizofinal_cliente_falecido>(this.attach_Juizofinal_cliente_falecidos), new Action<Juizofinal_cliente_falecido>(this.detach_Juizofinal_cliente_falecidos));
			this._Juizofinal_falecidos = new EntitySet<Juizofinal_falecido>(new Action<Juizofinal_falecido>(this.attach_Juizofinal_falecidos), new Action<Juizofinal_falecido>(this.detach_Juizofinal_falecidos));
			this._Juizofinal_falecido1 = default(EntityRef<Juizofinal_falecido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_falecido", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_falecido
		{
			get
			{
				return this._ID_falecido;
			}
			set
			{
				if ((this._ID_falecido != value))
				{
					this.OnID_falecidoChanging(value);
					this.SendPropertyChanging();
					this._ID_falecido = value;
					this.SendPropertyChanged("ID_falecido");
					this.OnID_falecidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_falecido_Pai", DbType="Int")]
		public System.Nullable<int> ID_falecido_Pai
		{
			get
			{
				return this._ID_falecido_Pai;
			}
			set
			{
				if ((this._ID_falecido_Pai != value))
				{
					if (this._Juizofinal_falecido1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_falecido_PaiChanging(value);
					this.SendPropertyChanging();
					this._ID_falecido_Pai = value;
					this.SendPropertyChanged("ID_falecido_Pai");
					this.OnID_falecido_PaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_falecido", DbType="VarChar(100)")]
		public string Nome_falecido
		{
			get
			{
				return this._Nome_falecido;
			}
			set
			{
				if ((this._Nome_falecido != value))
				{
					this.OnNome_falecidoChanging(value);
					this.SendPropertyChanging();
					this._Nome_falecido = value;
					this.SendPropertyChanged("Nome_falecido");
					this.OnNome_falecidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_nasceimento", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_nasceimento
		{
			get
			{
				return this._data_nasceimento;
			}
			set
			{
				if ((this._data_nasceimento != value))
				{
					this.Ondata_nasceimentoChanging(value);
					this.SendPropertyChanging();
					this._data_nasceimento = value;
					this.SendPropertyChanged("data_nasceimento");
					this.Ondata_nasceimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_morte", DbType="DateTime")]
		public System.Nullable<System.DateTime> data_morte
		{
			get
			{
				return this._data_morte;
			}
			set
			{
				if ((this._data_morte != value))
				{
					this.Ondata_morteChanging(value);
					this.SendPropertyChanging();
					this._data_morte = value;
					this.SendPropertyChanged("data_morte");
					this.Ondata_morteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_epitafio", DbType="VarChar(500)")]
		public string epitafio
		{
			get
			{
				return this._epitafio;
			}
			set
			{
				if ((this._epitafio != value))
				{
					this.OnepitafioChanging(value);
					this.SendPropertyChanging();
					this._epitafio = value;
					this.SendPropertyChanged("epitafio");
					this.OnepitafioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Inclusao", DbType="DateTime NOT NULL")]
		public System.DateTime DT_Inclusao
		{
			get
			{
				return this._DT_Inclusao;
			}
			set
			{
				if ((this._DT_Inclusao != value))
				{
					this.OnDT_InclusaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Inclusao = value;
					this.SendPropertyChanged("DT_Inclusao");
					this.OnDT_InclusaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Alteracao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Alteracao
		{
			get
			{
				return this._DT_Alteracao;
			}
			set
			{
				if ((this._DT_Alteracao != value))
				{
					this.OnDT_AlteracaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Alteracao = value;
					this.SendPropertyChanged("DT_Alteracao");
					this.OnDT_AlteracaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Exclusao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Exclusao
		{
			get
			{
				return this._DT_Exclusao;
			}
			set
			{
				if ((this._DT_Exclusao != value))
				{
					this.OnDT_ExclusaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Exclusao = value;
					this.SendPropertyChanged("DT_Exclusao");
					this.OnDT_ExclusaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_falecido_busca", DbType="VarChar(100)")]
		public string Nome_falecido_busca
		{
			get
			{
				return this._Nome_falecido_busca;
			}
			set
			{
				if ((this._Nome_falecido_busca != value))
				{
					this.OnNome_falecido_buscaChanging(value);
					this.SendPropertyChanging();
					this._Nome_falecido_busca = value;
					this.SendPropertyChanged("Nome_falecido_busca");
					this.OnNome_falecido_buscaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_mae", DbType="VarChar(50)")]
		public string Nome_mae
		{
			get
			{
				return this._Nome_mae;
			}
			set
			{
				if ((this._Nome_mae != value))
				{
					this.OnNome_maeChanging(value);
					this.SendPropertyChanging();
					this._Nome_mae = value;
					this.SendPropertyChanged("Nome_mae");
					this.OnNome_maeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_pai", DbType="VarChar(50)")]
		public string Nome_pai
		{
			get
			{
				return this._Nome_pai;
			}
			set
			{
				if ((this._Nome_pai != value))
				{
					this.OnNome_paiChanging(value);
					this.SendPropertyChanging();
					this._Nome_pai = value;
					this.SendPropertyChanged("Nome_pai");
					this.OnNome_paiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade_nascimento", DbType="VarChar(50)")]
		public string cidade_nascimento
		{
			get
			{
				return this._cidade_nascimento;
			}
			set
			{
				if ((this._cidade_nascimento != value))
				{
					this.Oncidade_nascimentoChanging(value);
					this.SendPropertyChanging();
					this._cidade_nascimento = value;
					this.SendPropertyChanged("cidade_nascimento");
					this.Oncidade_nascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade_morte", DbType="VarChar(50)")]
		public string cidade_morte
		{
			get
			{
				return this._cidade_morte;
			}
			set
			{
				if ((this._cidade_morte != value))
				{
					this.Oncidade_morteChanging(value);
					this.SendPropertyChanging();
					this._cidade_morte = value;
					this.SendPropertyChanged("cidade_morte");
					this.Oncidade_morteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_causa_morte", DbType="VarChar(50)")]
		public string causa_morte
		{
			get
			{
				return this._causa_morte;
			}
			set
			{
				if ((this._causa_morte != value))
				{
					this.Oncausa_morteChanging(value);
					this.SendPropertyChanging();
					this._causa_morte = value;
					this.SendPropertyChanged("causa_morte");
					this.Oncausa_morteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_1", DbType="VarChar(100)")]
		public string foto_1
		{
			get
			{
				return this._foto_1;
			}
			set
			{
				if ((this._foto_1 != value))
				{
					this.Onfoto_1Changing(value);
					this.SendPropertyChanging();
					this._foto_1 = value;
					this.SendPropertyChanged("foto_1");
					this.Onfoto_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_2", DbType="VarChar(100)")]
		public string foto_2
		{
			get
			{
				return this._foto_2;
			}
			set
			{
				if ((this._foto_2 != value))
				{
					this.Onfoto_2Changing(value);
					this.SendPropertyChanging();
					this._foto_2 = value;
					this.SendPropertyChanged("foto_2");
					this.Onfoto_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_foto_3", DbType="VarChar(100)")]
		public string foto_3
		{
			get
			{
				return this._foto_3;
			}
			set
			{
				if ((this._foto_3 != value))
				{
					this.Onfoto_3Changing(value);
					this.SendPropertyChanging();
					this._foto_3 = value;
					this.SendPropertyChanged("foto_3");
					this.Onfoto_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estrelas_brancas", DbType="Int")]
		public System.Nullable<int> estrelas_brancas
		{
			get
			{
				return this._estrelas_brancas;
			}
			set
			{
				if ((this._estrelas_brancas != value))
				{
					this.Onestrelas_brancasChanging(value);
					this.SendPropertyChanging();
					this._estrelas_brancas = value;
					this.SendPropertyChanged("estrelas_brancas");
					this.Onestrelas_brancasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estrelas_azuis", DbType="Int")]
		public System.Nullable<int> estrelas_azuis
		{
			get
			{
				return this._estrelas_azuis;
			}
			set
			{
				if ((this._estrelas_azuis != value))
				{
					this.Onestrelas_azuisChanging(value);
					this.SendPropertyChanging();
					this._estrelas_azuis = value;
					this.SendPropertyChanged("estrelas_azuis");
					this.Onestrelas_azuisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estrelas_vermelhas", DbType="Int")]
		public System.Nullable<int> estrelas_vermelhas
		{
			get
			{
				return this._estrelas_vermelhas;
			}
			set
			{
				if ((this._estrelas_vermelhas != value))
				{
					this.Onestrelas_vermelhasChanging(value);
					this.SendPropertyChanging();
					this._estrelas_vermelhas = value;
					this.SendPropertyChanged("estrelas_vermelhas");
					this.Onestrelas_vermelhasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vela", DbType="Int")]
		public System.Nullable<int> vela
		{
			get
			{
				return this._vela;
			}
			set
			{
				if ((this._vela != value))
				{
					this.OnvelaChanging(value);
					this.SendPropertyChanging();
					this._vela = value;
					this.SendPropertyChanged("vela");
					this.OnvelaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profissao", DbType="VarChar(200)")]
		public string profissao
		{
			get
			{
				return this._profissao;
			}
			set
			{
				if ((this._profissao != value))
				{
					this.OnprofissaoChanging(value);
					this.SendPropertyChanging();
					this._profissao = value;
					this.SendPropertyChanged("profissao");
					this.OnprofissaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Juizofinal_falecido_Juizofinal_cliente_falecido", Storage="_Juizofinal_cliente_falecidos", ThisKey="ID_falecido", OtherKey="ID_falecido")]
		public EntitySet<Juizofinal_cliente_falecido> Juizofinal_cliente_falecidos
		{
			get
			{
				return this._Juizofinal_cliente_falecidos;
			}
			set
			{
				this._Juizofinal_cliente_falecidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Juizofinal_falecido_Juizofinal_falecido", Storage="_Juizofinal_falecidos", ThisKey="ID_falecido", OtherKey="ID_falecido_Pai")]
		public EntitySet<Juizofinal_falecido> Juizofinal_falecidos
		{
			get
			{
				return this._Juizofinal_falecidos;
			}
			set
			{
				this._Juizofinal_falecidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Juizofinal_falecido_Juizofinal_falecido", Storage="_Juizofinal_falecido1", ThisKey="ID_falecido_Pai", OtherKey="ID_falecido", IsForeignKey=true)]
		public Juizofinal_falecido Juizofinal_falecido1
		{
			get
			{
				return this._Juizofinal_falecido1.Entity;
			}
			set
			{
				Juizofinal_falecido previousValue = this._Juizofinal_falecido1.Entity;
				if (((previousValue != value) 
							|| (this._Juizofinal_falecido1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Juizofinal_falecido1.Entity = null;
						previousValue.Juizofinal_falecidos.Remove(this);
					}
					this._Juizofinal_falecido1.Entity = value;
					if ((value != null))
					{
						value.Juizofinal_falecidos.Add(this);
						this._ID_falecido_Pai = value.ID_falecido;
					}
					else
					{
						this._ID_falecido_Pai = default(Nullable<int>);
					}
					this.SendPropertyChanged("Juizofinal_falecido1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Juizofinal_cliente_falecidos(Juizofinal_cliente_falecido entity)
		{
			this.SendPropertyChanging();
			entity.Juizofinal_falecido = this;
		}
		
		private void detach_Juizofinal_cliente_falecidos(Juizofinal_cliente_falecido entity)
		{
			this.SendPropertyChanging();
			entity.Juizofinal_falecido = null;
		}
		
		private void attach_Juizofinal_falecidos(Juizofinal_falecido entity)
		{
			this.SendPropertyChanging();
			entity.Juizofinal_falecido1 = this;
		}
		
		private void detach_Juizofinal_falecidos(Juizofinal_falecido entity)
		{
			this.SendPropertyChanging();
			entity.Juizofinal_falecido1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Juizofinal_nivel_parentesco")]
	public partial class Juizofinal_nivel_parentesco
	{
		
		private int _ID;
		
		private bool _Ativo;
		
		private string _Nivel_parentesco;
		
		public Juizofinal_nivel_parentesco()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this._Ativo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_parentesco", DbType="VarChar(150)")]
		public string Nivel_parentesco
		{
			get
			{
				return this._Nivel_parentesco;
			}
			set
			{
				if ((this._Nivel_parentesco != value))
				{
					this._Nivel_parentesco = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Juizofinal_nivel_corporacao")]
	public partial class Juizofinal_nivel_corporacao
	{
		
		private int _ID;
		
		private bool _Ativo;
		
		private string _Nivel_corporacao;
		
		public Juizofinal_nivel_corporacao()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this._Ativo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_corporacao", DbType="VarChar(150)")]
		public string Nivel_corporacao
		{
			get
			{
				return this._Nivel_corporacao;
			}
			set
			{
				if ((this._Nivel_corporacao != value))
				{
					this._Nivel_corporacao = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Juizofinal_cliente")]
	public partial class Juizofinal_cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.Guid> _UserId;
		
		private int _ID_cliente;
		
		private string _Nome_cliente;
		
		private bool _Ativo;
		
		private string _Documento;
		
		private System.DateTime _DT_Inclusao;
		
		private System.Nullable<System.DateTime> _DT_Alteracao;
		
		private System.Nullable<System.DateTime> _DT_Exclusao;
		
		private System.Nullable<int> _Licenca_comprada;
		
		private System.Nullable<int> _Jazigo_comprado;
		
		private string _Email;
		
		private string _Nome_jazigo;
		
		private string _Nome_completo;
		
		private System.Nullable<bool> _Corporacao;
		
		private string _Nome_jazigo_corporacao;
		
		private EntitySet<Juizofinal_cliente_falecido> _Juizofinal_cliente_falecidos;
		
		private EntitySet<Juizofinal_jazigo> _Juizofinal_jazigos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdChanged();
    partial void OnID_clienteChanging(int value);
    partial void OnID_clienteChanged();
    partial void OnNome_clienteChanging(string value);
    partial void OnNome_clienteChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    partial void OnDocumentoChanging(string value);
    partial void OnDocumentoChanged();
    partial void OnDT_InclusaoChanging(System.DateTime value);
    partial void OnDT_InclusaoChanged();
    partial void OnDT_AlteracaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_AlteracaoChanged();
    partial void OnDT_ExclusaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_ExclusaoChanged();
    partial void OnLicenca_compradaChanging(System.Nullable<int> value);
    partial void OnLicenca_compradaChanged();
    partial void OnJazigo_compradoChanging(System.Nullable<int> value);
    partial void OnJazigo_compradoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNome_jazigoChanging(string value);
    partial void OnNome_jazigoChanged();
    partial void OnNome_completoChanging(string value);
    partial void OnNome_completoChanged();
    partial void OnCorporacaoChanging(System.Nullable<bool> value);
    partial void OnCorporacaoChanged();
    partial void OnNome_jazigo_corporacaoChanging(string value);
    partial void OnNome_jazigo_corporacaoChanged();
    #endregion
		
		public Juizofinal_cliente()
		{
			this._Juizofinal_cliente_falecidos = new EntitySet<Juizofinal_cliente_falecido>(new Action<Juizofinal_cliente_falecido>(this.attach_Juizofinal_cliente_falecidos), new Action<Juizofinal_cliente_falecido>(this.detach_Juizofinal_cliente_falecidos));
			this._Juizofinal_jazigos = new EntitySet<Juizofinal_jazigo>(new Action<Juizofinal_jazigo>(this.attach_Juizofinal_jazigos), new Action<Juizofinal_jazigo>(this.detach_Juizofinal_jazigos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_cliente
		{
			get
			{
				return this._ID_cliente;
			}
			set
			{
				if ((this._ID_cliente != value))
				{
					this.OnID_clienteChanging(value);
					this.SendPropertyChanging();
					this._ID_cliente = value;
					this.SendPropertyChanged("ID_cliente");
					this.OnID_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_cliente", DbType="VarChar(200)")]
		public string Nome_cliente
		{
			get
			{
				return this._Nome_cliente;
			}
			set
			{
				if ((this._Nome_cliente != value))
				{
					this.OnNome_clienteChanging(value);
					this.SendPropertyChanging();
					this._Nome_cliente = value;
					this.SendPropertyChanged("Nome_cliente");
					this.OnNome_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documento", DbType="VarChar(30)")]
		public string Documento
		{
			get
			{
				return this._Documento;
			}
			set
			{
				if ((this._Documento != value))
				{
					this.OnDocumentoChanging(value);
					this.SendPropertyChanging();
					this._Documento = value;
					this.SendPropertyChanged("Documento");
					this.OnDocumentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Inclusao", DbType="DateTime NOT NULL")]
		public System.DateTime DT_Inclusao
		{
			get
			{
				return this._DT_Inclusao;
			}
			set
			{
				if ((this._DT_Inclusao != value))
				{
					this.OnDT_InclusaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Inclusao = value;
					this.SendPropertyChanged("DT_Inclusao");
					this.OnDT_InclusaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Alteracao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Alteracao
		{
			get
			{
				return this._DT_Alteracao;
			}
			set
			{
				if ((this._DT_Alteracao != value))
				{
					this.OnDT_AlteracaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Alteracao = value;
					this.SendPropertyChanged("DT_Alteracao");
					this.OnDT_AlteracaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Exclusao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Exclusao
		{
			get
			{
				return this._DT_Exclusao;
			}
			set
			{
				if ((this._DT_Exclusao != value))
				{
					this.OnDT_ExclusaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Exclusao = value;
					this.SendPropertyChanged("DT_Exclusao");
					this.OnDT_ExclusaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Licenca_comprada", DbType="Int")]
		public System.Nullable<int> Licenca_comprada
		{
			get
			{
				return this._Licenca_comprada;
			}
			set
			{
				if ((this._Licenca_comprada != value))
				{
					this.OnLicenca_compradaChanging(value);
					this.SendPropertyChanging();
					this._Licenca_comprada = value;
					this.SendPropertyChanged("Licenca_comprada");
					this.OnLicenca_compradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jazigo_comprado", DbType="Int")]
		public System.Nullable<int> Jazigo_comprado
		{
			get
			{
				return this._Jazigo_comprado;
			}
			set
			{
				if ((this._Jazigo_comprado != value))
				{
					this.OnJazigo_compradoChanging(value);
					this.SendPropertyChanging();
					this._Jazigo_comprado = value;
					this.SendPropertyChanged("Jazigo_comprado");
					this.OnJazigo_compradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_jazigo", DbType="VarChar(200)")]
		public string Nome_jazigo
		{
			get
			{
				return this._Nome_jazigo;
			}
			set
			{
				if ((this._Nome_jazigo != value))
				{
					this.OnNome_jazigoChanging(value);
					this.SendPropertyChanging();
					this._Nome_jazigo = value;
					this.SendPropertyChanged("Nome_jazigo");
					this.OnNome_jazigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_completo", DbType="VarChar(150)")]
		public string Nome_completo
		{
			get
			{
				return this._Nome_completo;
			}
			set
			{
				if ((this._Nome_completo != value))
				{
					this.OnNome_completoChanging(value);
					this.SendPropertyChanging();
					this._Nome_completo = value;
					this.SendPropertyChanged("Nome_completo");
					this.OnNome_completoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Corporacao", DbType="Bit")]
		public System.Nullable<bool> Corporacao
		{
			get
			{
				return this._Corporacao;
			}
			set
			{
				if ((this._Corporacao != value))
				{
					this.OnCorporacaoChanging(value);
					this.SendPropertyChanging();
					this._Corporacao = value;
					this.SendPropertyChanged("Corporacao");
					this.OnCorporacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_jazigo_corporacao", DbType="VarChar(200)")]
		public string Nome_jazigo_corporacao
		{
			get
			{
				return this._Nome_jazigo_corporacao;
			}
			set
			{
				if ((this._Nome_jazigo_corporacao != value))
				{
					this.OnNome_jazigo_corporacaoChanging(value);
					this.SendPropertyChanging();
					this._Nome_jazigo_corporacao = value;
					this.SendPropertyChanged("Nome_jazigo_corporacao");
					this.OnNome_jazigo_corporacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Juizofinal_cliente_Juizofinal_cliente_falecido", Storage="_Juizofinal_cliente_falecidos", ThisKey="ID_cliente", OtherKey="ID_cliente")]
		public EntitySet<Juizofinal_cliente_falecido> Juizofinal_cliente_falecidos
		{
			get
			{
				return this._Juizofinal_cliente_falecidos;
			}
			set
			{
				this._Juizofinal_cliente_falecidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Juizofinal_cliente_Juizofinal_jazigo", Storage="_Juizofinal_jazigos", ThisKey="ID_cliente", OtherKey="ID_cliente")]
		public EntitySet<Juizofinal_jazigo> Juizofinal_jazigos
		{
			get
			{
				return this._Juizofinal_jazigos;
			}
			set
			{
				this._Juizofinal_jazigos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Juizofinal_cliente_falecidos(Juizofinal_cliente_falecido entity)
		{
			this.SendPropertyChanging();
			entity.Juizofinal_cliente = this;
		}
		
		private void detach_Juizofinal_cliente_falecidos(Juizofinal_cliente_falecido entity)
		{
			this.SendPropertyChanging();
			entity.Juizofinal_cliente = null;
		}
		
		private void attach_Juizofinal_jazigos(Juizofinal_jazigo entity)
		{
			this.SendPropertyChanging();
			entity.Juizofinal_cliente = this;
		}
		
		private void detach_Juizofinal_jazigos(Juizofinal_jazigo entity)
		{
			this.SendPropertyChanging();
			entity.Juizofinal_cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Juizofinal_jazigo")]
	public partial class Juizofinal_jazigo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_cliente;
		
		private int _ID_falecido;
		
		private bool _Ativo;
		
		private string _Nivel_parentesco;
		
		private string _Nome_falecido;
		
		private System.DateTime _DT_Inclusao;
		
		private System.Nullable<System.DateTime> _DT_Alteracao;
		
		private System.Nullable<System.DateTime> _DT_Exclusao;
		
		private string _Nome_jazigo;
		
		private System.Nullable<bool> _Corporativo;
		
		private EntityRef<Juizofinal_cliente> _Juizofinal_cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_clienteChanging(int value);
    partial void OnID_clienteChanged();
    partial void OnID_falecidoChanging(int value);
    partial void OnID_falecidoChanged();
    partial void OnAtivoChanging(bool value);
    partial void OnAtivoChanged();
    partial void OnNivel_parentescoChanging(string value);
    partial void OnNivel_parentescoChanged();
    partial void OnNome_falecidoChanging(string value);
    partial void OnNome_falecidoChanged();
    partial void OnDT_InclusaoChanging(System.DateTime value);
    partial void OnDT_InclusaoChanged();
    partial void OnDT_AlteracaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_AlteracaoChanged();
    partial void OnDT_ExclusaoChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_ExclusaoChanged();
    partial void OnNome_jazigoChanging(string value);
    partial void OnNome_jazigoChanged();
    partial void OnCorporativoChanging(System.Nullable<bool> value);
    partial void OnCorporativoChanged();
    #endregion
		
		public Juizofinal_jazigo()
		{
			this._Juizofinal_cliente = default(EntityRef<Juizofinal_cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_cliente", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_cliente
		{
			get
			{
				return this._ID_cliente;
			}
			set
			{
				if ((this._ID_cliente != value))
				{
					if (this._Juizofinal_cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_clienteChanging(value);
					this.SendPropertyChanging();
					this._ID_cliente = value;
					this.SendPropertyChanged("ID_cliente");
					this.OnID_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_falecido", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_falecido
		{
			get
			{
				return this._ID_falecido;
			}
			set
			{
				if ((this._ID_falecido != value))
				{
					this.OnID_falecidoChanging(value);
					this.SendPropertyChanging();
					this._ID_falecido = value;
					this.SendPropertyChanged("ID_falecido");
					this.OnID_falecidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ativo", DbType="Bit NOT NULL")]
		public bool Ativo
		{
			get
			{
				return this._Ativo;
			}
			set
			{
				if ((this._Ativo != value))
				{
					this.OnAtivoChanging(value);
					this.SendPropertyChanging();
					this._Ativo = value;
					this.SendPropertyChanged("Ativo");
					this.OnAtivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel_parentesco", DbType="VarChar(100)")]
		public string Nivel_parentesco
		{
			get
			{
				return this._Nivel_parentesco;
			}
			set
			{
				if ((this._Nivel_parentesco != value))
				{
					this.OnNivel_parentescoChanging(value);
					this.SendPropertyChanging();
					this._Nivel_parentesco = value;
					this.SendPropertyChanged("Nivel_parentesco");
					this.OnNivel_parentescoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_falecido", DbType="VarChar(200)")]
		public string Nome_falecido
		{
			get
			{
				return this._Nome_falecido;
			}
			set
			{
				if ((this._Nome_falecido != value))
				{
					this.OnNome_falecidoChanging(value);
					this.SendPropertyChanging();
					this._Nome_falecido = value;
					this.SendPropertyChanged("Nome_falecido");
					this.OnNome_falecidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Inclusao", DbType="DateTime NOT NULL")]
		public System.DateTime DT_Inclusao
		{
			get
			{
				return this._DT_Inclusao;
			}
			set
			{
				if ((this._DT_Inclusao != value))
				{
					this.OnDT_InclusaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Inclusao = value;
					this.SendPropertyChanged("DT_Inclusao");
					this.OnDT_InclusaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Alteracao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Alteracao
		{
			get
			{
				return this._DT_Alteracao;
			}
			set
			{
				if ((this._DT_Alteracao != value))
				{
					this.OnDT_AlteracaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Alteracao = value;
					this.SendPropertyChanged("DT_Alteracao");
					this.OnDT_AlteracaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Exclusao", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Exclusao
		{
			get
			{
				return this._DT_Exclusao;
			}
			set
			{
				if ((this._DT_Exclusao != value))
				{
					this.OnDT_ExclusaoChanging(value);
					this.SendPropertyChanging();
					this._DT_Exclusao = value;
					this.SendPropertyChanged("DT_Exclusao");
					this.OnDT_ExclusaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome_jazigo", DbType="VarChar(100)")]
		public string Nome_jazigo
		{
			get
			{
				return this._Nome_jazigo;
			}
			set
			{
				if ((this._Nome_jazigo != value))
				{
					this.OnNome_jazigoChanging(value);
					this.SendPropertyChanging();
					this._Nome_jazigo = value;
					this.SendPropertyChanged("Nome_jazigo");
					this.OnNome_jazigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Corporativo", DbType="Bit")]
		public System.Nullable<bool> Corporativo
		{
			get
			{
				return this._Corporativo;
			}
			set
			{
				if ((this._Corporativo != value))
				{
					this.OnCorporativoChanging(value);
					this.SendPropertyChanging();
					this._Corporativo = value;
					this.SendPropertyChanged("Corporativo");
					this.OnCorporativoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Juizofinal_cliente_Juizofinal_jazigo", Storage="_Juizofinal_cliente", ThisKey="ID_cliente", OtherKey="ID_cliente", IsForeignKey=true)]
		public Juizofinal_cliente Juizofinal_cliente
		{
			get
			{
				return this._Juizofinal_cliente.Entity;
			}
			set
			{
				Juizofinal_cliente previousValue = this._Juizofinal_cliente.Entity;
				if (((previousValue != value) 
							|| (this._Juizofinal_cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Juizofinal_cliente.Entity = null;
						previousValue.Juizofinal_jazigos.Remove(this);
					}
					this._Juizofinal_cliente.Entity = value;
					if ((value != null))
					{
						value.Juizofinal_jazigos.Add(this);
						this._ID_cliente = value.ID_cliente;
					}
					else
					{
						this._ID_cliente = default(int);
					}
					this.SendPropertyChanged("Juizofinal_cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
